## 2025-09-24

### Numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

In [4]:
L = range(1000)
%timeit L2 = [i**2 for i in L]

272 μs ± 23.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
arr = np.arange(1000)
%timeit arr2 = arr*2

1.55 μs ± 33.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
alist = [1,2,3,4,5,6]

In [7]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [8]:
blist = [1,2,None,4,5,6]

In [9]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
ar1.dtype

dtype('int64')

In [11]:
ar2 = np.array([1.1, 2.2, 3.3])

In [13]:
print(ar2)

[1.1 2.2 3.3]


In [14]:
ar2.dtype

dtype('float64')

In [16]:
list_data = [1, 2., 3]

ar3 = np.array(list_data, dtype='int')

print(ar3)
print(ar3.dtype)

[1 2 3]
int64


In [17]:
np.array([1,2, np.nan,4])

array([ 1.,  2., nan,  4.])

In [19]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [20]:
arr2 = np.array([[1,2,3,4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [21]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [28]:
arr3 = arr2.reshape(2, -1, 3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [29]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [30]:
print(alist+blist)
print(alist-blist)
print(alist*blist)
print(alist/blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [31]:
print(alist+2)
print(alist-2)
print(alist*2)
print(alist/2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [32]:
a= np.array([1,2,3])
b= np.array([10,20,30])

In [34]:
print(2*a+b)
print(a==2)
print(b>10)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [ ]:
alist = [[0, 1, 2], [3, 4, 5]]
# 0, 1, 5 뽑기

In [36]:
print(alist[0][0])
print(alist[0][1])
print(alist[1][2])

0
1
5


In [49]:
# 0, 1 슬라이싱
# 4, 5 슬라이싱
# 1, 4 를 하나의 리스트에 담아서 보여주세요(슬라이싱?)

print(alist[0][:2])
print(alist[1][1:])
print([alist[0][1],alist[1][1]])

[0, 1]
[4, 5]
[1, 4]


In [53]:
blist = np.array([[0, 1, 2], [3, 4, 5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
print(blist[0,0], blist[0,1])
print(blist[1,1], blist[1,2])
print(blist[0,1], blist[1,1])

print(blist[0,:2])
print(blist[1,1:])
print(blist[: ,1])

0 1
4 5
1 4
[0 1]
[4 5]
[1 4]


In [66]:
print(blist[[0,1],[1,1]])

[1 4]


In [52]:
print(blist[0, 0], blist[0, 1], blist[1, 2])

0 1 5


In [72]:
a = np.array([[0,1,2,3], [4,5,6,7]])
print(a[0,:3])
print(a[:,1])
print(a[1,1:])
print(a[:,:2])

[0 1 2]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [82]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])

print(a)
print(a[:,:2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]


In [83]:
print(a[:2,:2])

[[0 1]
 [4 5]]


In [84]:
print(a[:2,1:])

[[1 2 3]
 [5 6 7]]


In [86]:
a= np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [90]:
a= np.array([1,2,3,4,5,6,7,8,9,10])
idx = [0,2,5]
a[idx]

array([1, 3, 6])

In [93]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
b[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [95]:
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [96]:
arr = np.array([1,2,3,4,5,6,7,8])

In [98]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [99]:
arr[arr%2==0]

array([2, 4, 6, 8])

In [100]:
arr[arr%2!=0]

array([1, 3, 5, 7])

In [101]:
a= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [111]:
a[:, [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [119]:
a[[2, 1, 0],:]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [121]:
data = np.array([1, 4, 9, 16])

In [122]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [123]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [124]:
np.sum(data)

np.int64(30)

In [125]:
np.mean(data)

np.float64(7.5)

In [126]:
np.std(data)

np.float64(5.678908345800274)

In [127]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [128]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [129]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [133]:
x[(x%3==0) & (x%4==1)]

array([9])

### Pandas

In [135]:
!pip install pandas

     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.3 MB 15.5 MB/s eta 0:00:01
     --- ------------------------------------ 1.0/11.3 MB 16.4 MB/s eta 0:00:01
     --- ------------------------------------ 1.0/11.3 MB 16.4 MB/s eta 0:00:01
     --- ------------------------------------ 1.0/11.3 MB 16.4 MB/s eta 0:00:01
     ------ --------------------------------- 1.8/11.3 MB 8.2 MB/s eta 0:00:02
     ------- -------------------------------- 2.1/11.3 MB 8.9 MB/s eta 0:00:02
     ------- -------------------------------- 2.2/11.3 MB 6.8 MB/s eta 0:00:02
     ---------- ----------------------------- 3.0/11.3 MB 8.3 MB/s eta 0:00:02
     ------------- -------------------------- 3.8/11.3 MB 9.4 MB/s eta 0:00:01
     --------------- ------------------------ 4.5/11.3 MB 10.2 MB/s eta 0:00:01
     ---------------- ----------------------- 4.7/11.3 MB 9.3 MB/s eta 0:00:01
     ----------------- ---------------------- 5.1/11.3


[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+13
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [4]:
pd.options.display.float_format = '{:,.0f}'.format

In [144]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 464.0+ bytes


In [146]:
df.describe()

나이   키                 재산
count   7   7                  5
mean   34 190  2,300,278,000,120
std    13  36  5,142,800,956,894
min    18 170                600
25%    26 172         50,000,000
50%    32 177        340,000,000
75%    39 184      1,000,000,000
max    58 270 11,500,000,000,000

In [147]:
df.head()

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000

In [148]:
df.tail()

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [149]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [150]:
type(df['국적'])

pandas.core.series.Series

In [152]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [153]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [155]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [156]:
df.nlargest(7, '나이')

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000
3   원더우먼  27     공주  데미스키라  178                NaN
5   캡틴마블  25    파일럿     미국  170        340,000,000
2  스파이더맨  18   고등학생     미국  177                600

In [157]:
df.nlargest(7, '키')

이름  나이     직업     국적    키                 재산
4     헐크  33  핵물리학자     미국  270      1,000,000,000
1     토르  45      신  아스가르드  190                NaN
3   원더우먼  27     공주  데미스키라  178                NaN
2  스파이더맨  18   고등학생     미국  177                600
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [158]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [159]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [160]:
df[:3]

이름  나이    직업     국적    키                 재산
0   아이언맨  58   CEO     미국  174 11,500,000,000,000
1     토르  45     신  아스가르드  190                NaN
2  스파이더맨  18  고등학생     미국  177                600

In [161]:
# df.iloc[행번호, 열번호]
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
df.iloc[1:4][:]  

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [165]:
df.iloc[[1, 3, 6]]

이름  나이   직업     국적    키         재산
1     토르  45    신  아스가르드  190        NaN
3   원더우먼  27   공주  데미스키라  178        NaN
6  블랙위도우  32  스파이    러시아  170 50,000,000

In [169]:
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [ ]:
# df.loc[행이름, 열이름]

In [170]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [172]:
df.loc[2:5]

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000

In [173]:
df.loc[:2, ['이름', '직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [174]:
df.loc[3:, '국적':'재산']

국적    키            재산
3  데미스키라  178           NaN
4     미국  270 1,000,000,000
5     미국  170   340,000,000
6    러시아  170    50,000,000

In [175]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [176]:
df[df['나이']>30]

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
#나이가 30초과, 50미만인 사람들의 전체 레코드
df[(df['나이']>30)&(df['나이']<50)]

이름  나이     직업     국적    키            재산
1     토르  45      신  아스가르드  190           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [181]:
#키가 180이상인 레코드의 이름과 나이 컬럼만 출력
df.loc[df['키']>=180, ['이름', '나이']]

이름  나이
1  토르  45
4  헐크  33

In [182]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [183]:
df['전투력'] = 98

In [184]:
df

이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   98
1     토르  45      신  아스가르드  190                NaN   98
2  스파이더맨  18   고등학생     미국  177                600   98
3   원더우먼  27     공주  데미스키라  178                NaN   98
4     헐크  33  핵물리학자     미국  270      1,000,000,000   98
5   캡틴마블  25    파일럿     미국  170        340,000,000   98
6  블랙위도우  32    스파이    러시아  170         50,000,000   98

In [185]:
df['전투력'] = df['전투력'] - 5
df

이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   93
1     토르  45      신  아스가르드  190                NaN   93
2  스파이더맨  18   고등학생     미국  177                600   93
3   원더우먼  27     공주  데미스키라  178                NaN   93
4     헐크  33  핵물리학자     미국  270      1,000,000,000   93
5   캡틴마블  25    파일럿     미국  170        340,000,000   93
6  블랙위도우  32    스파이    러시아  170         50,000,000   93

In [ ]:
df.drop(columns=['전투력'], inplace = True)  
#inplace = True 로 확정시켜야 원본에 반영됨
#df = df.drop(columns=['전투력']) -> 이걸로 해도 됨

In [189]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
df.info()               # 결측치 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 464.0+ bytes


In [ ]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [194]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [195]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [ ]:
df.dropna()                 #inplace = True 해야 원본에 반영됨

이름  나이     직업   국적    키                 재산
0   아이언맨  58    CEO   미국  174 11,500,000,000,000
2  스파이더맨  18   고등학생   미국  177                600
4     헐크  33  핵물리학자   미국  270      1,000,000,000
5   캡틴마블  25    파일럿   미국  170        340,000,000
6  블랙위도우  32    스파이  러시아  170         50,000,000

In [197]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
df = df.fillna(method='ffill')      

C:\Users\el008\AppData\Local\Temp\ipykernel_25480\569672361.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')


In [199]:
df['재산'].fillna(df['재산'].mean())

0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64

In [203]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190 11,500,000,000,000
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                600
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [204]:
df.iloc[5, 1] = np.nan
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190 11,500,000,000,000
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                600
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블 NaN    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [209]:
df['나이'] = df['나이'].fillna(df['나이'].mean())

In [5]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [3]:
def add_cm(height):
    return str(height) + 'cm'

df['키'] = df['키'].apply(add_cm)

In [4]:
df

이름  나이     직업     국적      키            재산
0   아이언맨  58    CEO     미국  174cm  1.150000e+13
1     토르  45      신  아스가르드  190cm           NaN
2  스파이더맨  18   고등학생     미국  177cm  6.000000e+02
3   원더우먼  27     공주  데미스키라  178cm           NaN
4     헐크  33  핵물리학자     미국  270cm  1.000000e+09
5   캡틴마블  25    파일럿     미국  170cm  3.400000e+08
6  블랙위도우  32    스파이    러시아  170cm  5.000000e+07

In [5]:
# df = pd.read_csv('heroes.csv')
# 초기화할때 사용

In [ ]:
def add_cm(height):
    return str(height) + 'cm'
def remove_cm(b):
    #cm 많이 붙여서 cmcmcm 삭제하고 cm 하나 붙이는 과정                           
    part = b.replace('cmcmcm', '')
    part_float = float(part)
    return str(part_float) + 'cm'

#df['키'] = df['키'].apply(lambda a: str(a)+'cm')
df['키'] = df['키'].apply(remove_cm)
#df

In [15]:
df

이름  나이     직업     국적        키            재산
0   아이언맨  58    CEO     미국  174.0cm  1.150000e+13
1     토르  45      신  아스가르드  190.0cm           NaN
2  스파이더맨  18   고등학생     미국  177.0cm  6.000000e+02
3   원더우먼  27     공주  데미스키라  178.0cm           NaN
4     헐크  33  핵물리학자     미국  270.0cm  1.000000e+09
5   캡틴마블  25    파일럿     미국  170.0cm  3.400000e+08
6  블랙위도우  32    스파이    러시아  170.0cm  5.000000e+07

In [17]:
df.groupby('국적')['나이'].mean()

국적
데미스키라    27.0
러시아      32.0
미국       33.5
아스가르드    45.0
Name: 나이, dtype: float64

In [18]:
df.groupby('국적')['재산'].mean()

국적
데미스키라             NaN
러시아      5.000000e+07
미국       2.875335e+12
아스가르드             NaN
Name: 재산, dtype: float64